### ISSUE TITLE
libtls: ClientHello: extension signature algorithms cert

### ISSUE THREAD

**Issue by ryru** [bytinbit/strongswan#24]
Aufwandschätzung:
soll=3 Stunden

This extension indicates which signature algorithms the client supports. This can influence the certificate that the server presents to the client, as well as the signature that is sent by the server in the CertificateVerify record. 

https://tls13.ulfheim.net/

Consider:
- [4.2.3.  Signature Algorithms](https://tools.ietf.org/html/rfc8446#section-4.2.3)

**Comment by bytinbit** [comment]
RFC 8446, 41: "Implementations which have the same policy in both cases MAY omit the "signature_algorithms_cert" extension".
In other words: The two maintainers must decide if we have the same policy or not and thus must implement this extension or not in strongSwan libtls.
