### ISSUE TITLE
libtls: ClientHello: extension key share

### ISSUE THREAD

**Issue by ryru** [bytinbit/strongswan#25]
Aufwandschätzung:
soll=3 Stunden

The client sends one or more public keys using an algorithm that it thinks the server will support. This allows the rest of the handshake after the ClientHello and ServerHello messages to be encrypted, unlike previous protocol versions where the handshake was sent in the clear. 

https://tls13.ulfheim.net/

Consider:
- [4.2.8.  Key Share](https://tools.ietf.org/html/rfc8446#section-4.2.8)

**Comment by bytinbit** [comment]
Currently, there's the magic value `0x001D` in the code, it does not accept the enum-value of CURVE_25519 (32) out of unknown reasons.
