### ISSUE TITLE
libtls: Decrypt traffic by exporting client key material

### ISSUE THREAD

**Issue by bytinbit** [bytinbit/strongswan#30]
Aufwandschätzung:
soll=4 Stunden

Used for debugging, since TLS 1.3 encrypts traffic much faster in the handshake process than TLS 1.2. This concerns only the test-setup with an openssl-server and a strongSwan TLS client.

**Comment by ryru** [comment]
- https://wiki.wireshark.org/TLS#TLS_Decryption
- https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Key_Log_Format
